// =============================================================================
// STYLES - TaxiDash Madrid
// =============================================================================
import { StyleSheet, Platform, Dimensions } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export 
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  // Offline Banner
  offlineBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DC2626',
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 8,
  },
  offlineBannerText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  offlineBannerClose: {
    padding: 4,
  },
  // NEW: Dropdown styles
  dropdownsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
  },
  dropdownSelector: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  dropdownSelectorHidden: {
    opacity: 0.3,
  },
  dropdownSelectorText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  chatButtonCompact: {
    backgroundColor: '#6366F1',
    padding: 10,
    borderRadius: 10,
  },
  sosButtonCompact: {
    backgroundColor: '#1E293B',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#374151',
  },
  timeRangeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
  },
  timeWindowButtonsInline: {
    flexDirection: 'row',
    backgroundColor: '#1E293B',
    borderRadius: 10,
    padding: 4,
    gap: 4,
  },
  timeWindowButtonSmall: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  activeTimeWindowSmall: {
    backgroundColor: '#6366F1',
  },
  timeWindowTextSmall: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
  },
  activeTimeWindowTextSmall: {
    color: '#FFFFFF',
  },
  timeRangeDropdownFull: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  timeRangeDropdownFullActive: {
    borderColor: '#10B981',
    backgroundColor: '#10B98115',
  },
  timeRangeDropdownTextFull: {
    flex: 1,
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '500',
  },
  timeRangeDropdownTextFullActive: {
    color: '#10B981',
  },
  dropdownOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  dropdownMenu: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 8,
    width: '100%',
    maxWidth: 320,
    borderWidth: 1,
    borderColor: '#334155',
  },
  dropdownMenuTitle: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
    marginBottom: 4,
  },
  dropdownMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 10,
    gap: 12,
  },
  dropdownMenuItemActive: {
    backgroundColor: '#6366F120',
  },
  dropdownMenuItemText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
  dropdownMenuItemTextActive: {
    color: '#6366F1',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 40 : 10,
    paddingBottom: 15,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#94A3B8',
    marginTop: 4,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  userSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  adminButton: {
    padding: 8,
    backgroundColor: '#F59E0B22',
    borderRadius: 8,
  },
  userButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1E293B',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  usernameText: {
    color: '#6366F1',
    fontSize: 13,
    fontWeight: '500',
  },
  loginButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1E293B',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  loginButtonText: {
    color: '#6366F1',
    fontSize: 13,
    fontWeight: '500',
  },
  notificationToggle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  switch: {
    marginLeft: 8,
    transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }],
  },
  loginModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loginModalContent: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 20,
    width: '100%',
    maxWidth: 350,
  },
  loginModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  loginModalTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
  },
  settingsButton: {
    padding: 8,
    marginRight: 8,
  },
  settingsModal: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxWidth: 400,
  },
  settingsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
    paddingBottom: 15,
  },
  settingsTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
  },
  settingsSection: {
    marginBottom: 20,
  },
  settingsSectionTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 5,
  },
  settingsDescription: {
    color: '#94A3B8',
    fontSize: 13,
    marginBottom: 15,
  },
  gpsOptions: {
    gap: 10,
  },
  gpsOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 15,
    gap: 12,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  gpsOptionActive: {
    borderColor: '#10B981',
    backgroundColor: '#10B98120',
  },
  gpsOptionText: {
    flex: 1,
    color: '#94A3B8',
    fontSize: 16,
    fontWeight: '500',
  },
  gpsOptionTextActive: {
    color: '#FFFFFF',
  },
  settingsCloseButton: {
    backgroundColor: '#6366F1',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
  },
  settingsCloseButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  loginInput: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    padding: 15,
    color: '#FFFFFF',
    fontSize: 16,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#334155',
  },
  loginSubmitButton: {
    backgroundColor: '#6366F1',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 5,
  },
  loginSubmitText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 12,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#1E293B',
    gap: 8,
  },
  activeTabTrains: {
    backgroundColor: '#6366F1',
  },
  activeTabFlights: {
    backgroundColor: '#10B981',
  },
  activeTabStreet: {
    backgroundColor: '#F59E0B',
  },
  activeTabEvents: {
    backgroundColor: '#EC4899',
  },
  tabText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#94A3B8',
  },
  activeTabText: {
    color: '#FFFFFF',
  },
  timeWindowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    gap: 12,
  },
  timeWindowLabel: {
    color: '#94A3B8',
    fontSize: 14,
  },
  timeWindowButtons: {
    flexDirection: 'row',
    backgroundColor: '#1E293B',
    borderRadius: 8,
    padding: 4,
  },
  timeWindowButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
  },
  activeTimeWindow: {
    backgroundColor: '#334155',
  },
  timeWindowText: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '500',
  },
  activeTimeWindowText: {
    color: '#FFFFFF',
  },
  shiftContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 10,
    gap: 12,
  },
  shiftLabel: {
    color: '#94A3B8',
    fontSize: 14,
  },
  shiftButtons: {
    flexDirection: 'row',
    backgroundColor: '#1E293B',
    borderRadius: 8,
    padding: 4,
    gap: 4,
  },
  shiftButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    gap: 6,
  },
  activeShiftDay: {
    backgroundColor: '#F59E0B',
  },
  activeShiftAll: {
    backgroundColor: '#6366F1',
  },
  activeShiftNight: {
    backgroundColor: '#8B5CF6',
  },
  shiftText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '500',
  },
  activeShiftText: {
    color: '#FFFFFF',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  lastUpdateWithRefresh: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  refreshButtonSmall: {
    padding: 8,
    backgroundColor: '#1E293B',
    borderRadius: 8,
  },
  lastUpdateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    paddingHorizontal: 5,
  },
  lastUpdate: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  lastUpdateText: {
    color: '#64748B',
    fontSize: 12,
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 6,
  },
  refreshText: {
    color: '#6366F1',
    fontSize: 12,
    fontWeight: '500',
  },
  refreshTextDisabled: {
    color: '#64748B',
  },
  nightTimeMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E293B',
    borderRadius: 10,
    padding: 12,
    marginBottom: 15,
    gap: 8,
    borderWidth: 1,
    borderColor: '#F59E0B',
  },
  nightTimeText: {
    color: '#F59E0B',
    fontSize: 12,
    flex: 1,
    textAlign: 'center',
  },
  comparisonContainer: {
    gap: 15,
  },
  stationCard: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 20,
    borderWidth: 3,
    borderColor: '#4B5563',
    marginBottom: 35,
    marginTop: 20,
    marginHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  winnerCard: {
    borderColor: '#F59E0B',
    backgroundColor: '#1E293B',
  },
  // Station/Terminal Alert Card Styles
  stationAlertCard: {
    borderColor: '#EF4444',
    backgroundColor: '#1E293B',
  },
  alertBadgesContainer: {
    position: 'absolute',
    top: -12,
    left: 20,
    right: 80,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    zIndex: 10,
  },
  alertBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    gap: 5,
  },
  alertBadgeSinTaxis: {
    backgroundColor: '#EF4444',
  },
  alertBadgeBarandilla: {
    backgroundColor: '#F59E0B',
  },
  alertBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  alertBadgeTime: {
    color: '#FFFFFF',
    fontSize: 9,
    opacity: 0.8,
  },
  alertButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginTop: 12,
    marginBottom: 8,
  },
  alertButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  alertButtonSinTaxis: {
    backgroundColor: '#DC262680',
    borderWidth: 1,
    borderColor: '#EF4444',
  },
  alertButtonBarandilla: {
    backgroundColor: '#D9770680',
    borderWidth: 1,
    borderColor: '#F59E0B',
  },
  alertButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  // Close alert button styles
  closeAlertButtonsContainer: {
    flexDirection: 'column',
    gap: 8,
    marginTop: 10,
  },
  closeAlertButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
  },
  closeAlertButtonSinTaxis: {
    backgroundColor: '#DC2626',
  },
  closeAlertButtonBarandilla: {
    backgroundColor: '#D97706',
  },
  closeAlertButtonDisabled: {
    opacity: 0.5,
  },
  closeAlertButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  winnerBadge: {
    position: 'absolute',
    top: -12,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F59E0B',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  winnerBadgeFlight: {
    top: -10,
    right: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  winnerBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  stationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 15,
  },
  stationName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  winnerText: {
    color: '#F59E0B',
  },
  arrivalCount: {
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 15,
  },
  peakHourContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 10,
    padding: 12,
    marginBottom: 15,
    gap: 8,
    borderWidth: 1,
    borderColor: '#F59E0B33',
  },
  peakHourText: {
    color: '#F59E0B',
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
  },
  peakHourCount: {
    backgroundColor: '#F59E0B',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    minWidth: 32,
    alignItems: 'center',
  },
  peakHourCountText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  arrivalNumber: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#6366F1',
  },
  winnerNumber: {
    color: '#F59E0B',
  },
  arrivalLabel: {
    fontSize: 14,
    color: '#94A3B8',
    marginTop: 4,
  },
  // New styles for XA - YP format
  arrivalScoreRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
  },
  arrivalNumberSmall: {
    fontSize: 36,
    fontWeight: 'bold',
  },
  arrivalSuffix: {
    fontSize: 16,
    fontWeight: '600',
    opacity: 0.8,
  },
  arrivalDivider: {
    fontSize: 24,
    color: '#64748B',
    marginHorizontal: 8,
  },
  scoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6366F115',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginTop: 8,
    gap: 6,
  },
  scoreText: {
    color: '#6366F1',
    fontSize: 14,
    fontWeight: '600',
  },
  arrivalsList: {
    gap: 8,
  },
  arrivalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 8,
    padding: 10,
  },
  arrivalTime: {
    backgroundColor: '#334155',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  timeText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  arrivalInfo: {
    flex: 1,
    marginLeft: 12,
  },
  trainTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  trainType: {
    color: '#6366F1',
    fontSize: 12,
    fontWeight: '600',
  },
  delayBadge: {
    backgroundColor: '#EF444433',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  earlyBadge: {
    backgroundColor: '#10B98133',
  },
  delayText: {
    color: '#EF4444',
    fontSize: 11,
    fontWeight: '700',
  },
  earlyText: {
    color: '#10B981',
    fontSize: 11,
    fontWeight: '700',
  },
  delayedTimeText: {
    color: '#EF4444',
  },
  scheduledTimeText: {
    color: '#64748B',
    fontSize: 10,
    textDecorationLine: 'line-through',
  },
  originText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  platformBadge: {
    backgroundColor: '#6366F1',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minWidth: 36,
    alignItems: 'center',
  },
  platformText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  vsSeparator: {
    alignItems: 'center',
    paddingVertical: 5,
  },
  vsText: {
    color: '#64748B',
    fontSize: 18,
    fontWeight: 'bold',
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 15,
    textAlign: 'center',
  },
  terminalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
  },
  terminalGroupsContainer: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  terminalGroupCard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    flex: 1,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  terminalGroupName: {
    color: '#10B981',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  terminalGroupTerminals: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 4,
  },
  terminalGroupTerminalText: {
    color: '#64748B',
    fontSize: 11,
    backgroundColor: '#334155',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  terminalCard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    width: '30%',
    minWidth: 90,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  winnerTerminalCard: {
    borderColor: '#F59E0B',
  },
  terminalName: {
    color: '#10B981',
    fontSize: 16,
    fontWeight: 'bold',
  },
  winnerTerminalText: {
    color: '#F59E0B',
  },
  terminalCount: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: 'bold',
    marginVertical: 4,
  },
  winnerTerminalCount: {
    color: '#F59E0B',
  },
  terminalLabel: {
    color: '#94A3B8',
    fontSize: 12,
  },
  flightsList: {
    marginTop: 15,
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 15,
  },
  flightsListContainer: {
    gap: 15,
  },
  flightsListTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 15,
  },
  noFlightsText: {
    color: '#94A3B8',
    fontSize: 14,
    textAlign: 'center',
    padding: 20,
  },
  flightItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  flightTime: {
    backgroundColor: '#10B981',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  flightTimeText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  flightInfo: {
    flex: 1,
    marginLeft: 12,
  },
  flightNumber: {
    color: '#10B981',
    fontSize: 14,
    fontWeight: '600',
  },
  flightOrigin: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  flightAirline: {
    color: '#94A3B8',
    fontSize: 12,
  },
  flightStatus: {
    alignItems: 'center',
    minWidth: 70,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#94A3B8',
  },
  statusOnTime: {
    color: '#10B981',
  },
  statusDelayed: {
    color: '#EF4444',
  },
  statusEarly: {
    color: '#3B82F6',
  },
  flightGate: {
    alignItems: 'center',
  },
  gateLabel: {
    color: '#64748B',
    fontSize: 10,
  },
  gateText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 100,
  },
  loadingText: {
    color: '#94A3B8',
    marginTop: 15,
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 100,
  },
  errorText: {
    color: '#EF4444',
    fontSize: 16,
    marginTop: 15,
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: '#6366F1',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  footer: {
    paddingVertical: 12,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#1E293B',
  },
  footerText: {
    color: '#64748B',
    fontSize: 11,
  },
  // Auth loading screen
  authLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  authLoadingText: {
    color: '#94A3B8',
    marginTop: 15,
    fontSize: 16,
  },
  // Login screen styles
  loginScreenContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loginScreenContent: {
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
  },
  loginHeader: {
    alignItems: 'center',
    marginBottom: 40,
  },
  loginLogoContainer: {
    flexDirection: 'row',
    marginBottom: 15,
  },
  loginAppTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  loginAppSubtitle: {
    fontSize: 14,
    color: '#94A3B8',
    textAlign: 'center',
  },
  loginFormContainer: {
    width: '100%',
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 25,
    marginBottom: 20,
  },
  loginFormTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 25,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 10,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#334155',
  },
  inputIcon: {
    padding: 15,
  },
  loginScreenInput: {
    flex: 1,
    padding: 15,
    paddingLeft: 0,
    color: '#FFFFFF',
    fontSize: 16,
  },
  loginScreenButton: {
    flexDirection: 'row',
    backgroundColor: '#6366F1',
    borderRadius: 10,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    gap: 10,
  },
  loginScreenButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  loginFooter: {
    color: '#64748B',
    fontSize: 12,
    textAlign: 'center',
  },
  // Street work styles
  streetContainer: {
    flex: 1,
  },
  hottestStreetCard: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 20,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#EF4444',
  },
  hottestStreetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  hottestStreetTitle: {
    color: '#EF4444',
    fontSize: 16,
    fontWeight: '600',
  },
  hottestStreetName: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  hottestStreetCount: {
    color: '#94A3B8',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 5,
  },
  hottestStreetInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 8,
  },
  distanceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B98133',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  distanceText: {
    color: '#10B981',
    fontSize: 13,
    fontWeight: '600',
  },
  rangeIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#374151',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    marginTop: 8,
    gap: 6,
  },
  rangeText: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '500',
  },
  navigateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3B82F6',
    borderRadius: 12,
    paddingVertical: 14,
    marginTop: 15,
    gap: 8,
  },
  navigateButtonStation: {
    backgroundColor: '#3B82F6',
  },
  navigateButtonTerminal: {
    backgroundColor: '#8B5CF6',
  },
  navigateButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  stationHotCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
  },
  terminalHotCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#8B5CF6',
  },
  // Alert styles for hottest cards in Street tab
  hottestCardWithAlert: {
    borderColor: '#EF4444',
    borderLeftColor: '#EF4444',
  },
  hottestAlertBadgesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 10,
  },
  scoreBadge: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 'auto',
  },
  scoreBadgeTerminal: {
    backgroundColor: '#8B5CF6',
  },
  scoreBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  scoreDetailsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 8,
    marginBottom: 4,
  },
  scoreDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  scoreDetailText: {
    color: '#9CA3AF',
    fontSize: 12,
  },
  lowArrivalsAlert: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    borderWidth: 1,
    borderColor: '#F59E0B',
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
    gap: 8,
  },
  lowArrivalsAlertText: {
    color: '#92400E',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  taxiExitsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B98122',
    padding: 8,
    borderRadius: 6,
    marginTop: 8,
    gap: 6,
  },
  taxiExitsText: {
    color: '#10B981',
    fontSize: 13,
    fontWeight: '500',
  },
  taxiExitsContainerSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B98122',
    padding: 4,
    borderRadius: 4,
    marginTop: 4,
    gap: 4,
  },
  taxiExitsTextSmall: {
    color: '#10B981',
    fontSize: 11,
    fontWeight: '500',
  },
  taxiStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    padding: 10,
    borderRadius: 8,
    marginTop: 8,
    gap: 8,
  },
  queueStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    padding: 10,
    borderRadius: 8,
    marginTop: 8,
    gap: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#6366F1',
  },
  taxiStatusText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  taxiTimeText: {
    color: '#9CA3AF',
    fontSize: 11,
  },
  taxiStatusContainerSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    padding: 6,
    borderRadius: 6,
    marginTop: 6,
    gap: 4,
  },
  queueStatusContainerSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    padding: 6,
    borderRadius: 6,
    marginTop: 6,
    gap: 4,
    borderLeftWidth: 2,
    borderLeftColor: '#6366F1',
  },
  taxiStatusTextSmall: {
    fontSize: 12,
  },
  taxiTimeTextSmall: {
    color: '#9CA3AF',
    fontSize: 9,
  },
  checkInButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    borderRadius: 10,
    paddingVertical: 12,
    marginTop: 15,
    gap: 8,
  },
  checkOutButton: {
    backgroundColor: '#EF4444',
  },
  checkInButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  checkInButtonSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: 10,
    gap: 4,
  },
  checkOutButtonSmall: {
    backgroundColor: '#EF4444',
  },
  checkInButtonTextSmall: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  mapContainer: {
    height: 250,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 15,
    backgroundColor: '#1E293B',
  },
  map: {
    flex: 1,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  mapOverlay: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: 'column',
    gap: 4,
  },
  mapOverlayText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  locationIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  locationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#22C55E',
  },
  locationIndicatorText: {
    color: '#22C55E',
    fontSize: 11,
    fontWeight: '600',
  },
  coordsDisplay: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  coordsText: {
    color: '#9CA3AF',
    fontSize: 10,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  streetButtonsContainer: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 15,
    alignItems: 'center',
  },
  streetButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    borderRadius: 16,
    gap: 10,
  },
  streetButtonLarge: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 25,
    borderRadius: 16,
    gap: 8,
  },
  loadButtonLarge: {
    backgroundColor: '#10B981',
  },
  unloadButtonLarge: {
    backgroundColor: '#F59E0B',
  },
  streetButtonTextLarge: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  streetButtonHint: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
  },
  streetRefreshButton: {
    backgroundColor: '#3B82F6',
    padding: 15,
    borderRadius: 12,
    marginLeft: 10,
  },
  loadButton: {
    backgroundColor: '#10B981',
  },
  unloadButton: {
    backgroundColor: '#F59E0B',
  },
  streetButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  streetStatsContainer: {
    flexDirection: 'row',
    gap: 15,
    marginBottom: 10,
  },
  streetStatCard: {
    flex: 1,
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
  },
  streetStatCardSmall: {
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  streetStatNumber: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: 'bold',
  },
  streetStatNumberSmall: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  streetStatLabel: {
    color: '#94A3B8',
    fontSize: 14,
    marginTop: 4,
  },
  streetStatLabelSmall: {
    color: '#94A3B8',
    fontSize: 12,
  },
  recentActivityContainer: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 15,
  },
  recentActivityTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 15,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    gap: 10,
  },
  activityTimeColumn: {
    alignItems: 'center',
    minWidth: 50,
  },
  activityTimeText: {
    color: '#6366F1',
    fontSize: 13,
    fontWeight: 'bold',
  },
  durationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B98133',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginTop: 4,
    gap: 2,
  },
  durationText: {
    color: '#10B981',
    fontSize: 10,
    fontWeight: '600',
  },
  distanceBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6366F133',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    marginTop: 2,
    gap: 2,
  },
  distanceTextSmall: {
    color: '#6366F1',
    fontSize: 10,
    fontWeight: '600',
  },
  activityInfo: {
    flex: 1,
  },
  activityAction: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  activityStreet: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  activityUser: {
    color: '#64748B',
    fontSize: 11,
  },
  taxiQuestionModal: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
  },
  taxiQuestionHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  taxiQuestionTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    marginTop: 12,
  },
  taxiQuestionSubtitle: {
    color: '#94A3B8',
    fontSize: 14,
    marginTop: 4,
  },
  taxiOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    width: '100%',
  },
  taxiOption: {
    flex: 1,
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#374151',
  },
  taxiOptionPoco: {
    borderWidth: 2,
    borderColor: '#10B981',
  },
  taxiOptionNormal: {
    borderWidth: 2,
    borderColor: '#F59E0B',
  },
  taxiOptionMucho: {
    borderWidth: 2,
    borderColor: '#EF4444',
  },
  // Queue options (gente esperando) - colores invertidos: poca=malo(rojo), mucha=bueno(verde)
  queueOptionPoco: {
    borderWidth: 2,
    borderColor: '#EF4444',
  },
  queueOptionNormal: {
    borderWidth: 2,
    borderColor: '#F59E0B',
  },
  queueOptionMucho: {
    borderWidth: 2,
    borderColor: '#10B981',
  },
  taxiOptionEmoji: {
    fontSize: 32,
    marginBottom: 8,
  },
  taxiOptionText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  taxiSkipButton: {
    marginTop: 20,
    padding: 12,
  },
  taxiSkipButtonText: {
    color: '#94A3B8',
    fontSize: 14,
  },
  // Destination Modal Styles
  destinationModal: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    padding: 25,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
  },
  destinationHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  destinationTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
    marginTop: 10,
    textAlign: 'center',
  },
  destinationSubtitle: {
    color: '#94A3B8',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  destinationInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 15,
    gap: 10,
  },
  destinationInputWithMic: {
    flex: 1,
    backgroundColor: '#374151',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#4B5563',
  },
  destinationInput: {
    backgroundColor: '#374151',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: '#FFFFFF',
    width: '100%',
    borderWidth: 2,
    borderColor: '#4B5563',
    marginBottom: 15,
  },
  micButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#374151',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#3B82F6',
  },
  micButtonActive: {
    backgroundColor: '#3B82F6',
    borderColor: '#3B82F6',
  },
  listeningIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 8,
  },
  listeningText: {
    color: '#3B82F6',
    fontSize: 14,
  },
  searchingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    gap: 8,
  },
  searchingText: {
    color: '#94A3B8',
    fontSize: 14,
  },
  suggestionsContainer: {
    maxHeight: 180,
    backgroundColor: '#1E293B',
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#374151',
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
    gap: 12,
  },
  suggestionTextContainer: {
    flex: 1,
  },
  suggestionAddress: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  suggestionM30Status: {
    fontSize: 12,
    marginTop: 4,
  },
  calculateButton: {
    backgroundColor: '#3B82F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: '100%',
    gap: 8,
  },
  calculateButtonDisabled: {
    opacity: 0.6,
  },
  calculateButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  fareResultContainer: {
    width: '100%',
    marginTop: 20,
  },
  fareResultBox: {
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    borderWidth: 3,
  },
  fareInsideM30: {
    backgroundColor: '#10B98122',
    borderColor: '#10B981',
  },
  fareOutsideM30: {
    backgroundColor: '#F59E0B22',
    borderColor: '#F59E0B',
  },
  fareLocationText: {
    color: '#94A3B8',
    fontSize: 14,
    marginBottom: 10,
  },
  fareMainText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  fareDivider: {
    height: 1,
    backgroundColor: '#4B5563',
    width: '80%',
    marginVertical: 12,
  },
  fareSupplementText: {
    color: '#F59E0B',
    fontSize: 20,
    fontWeight: 'bold',
  },
  navigateToDestButton: {
    backgroundColor: '#3B82F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: '100%',
    marginTop: 15,
    gap: 10,
  },
  navigateToDestButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  destinationCloseButton: {
    backgroundColor: '#64748B',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    width: '100%',
    marginTop: 15,
    gap: 8,
  },
  destinationCloseButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
  },
  // Street Fare styles
  streetFareResultContainer: {
    width: '100%',
    marginTop: 15,
  },
  streetFareBox: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#374151',
  },
  streetFareType: {
    fontSize: 14,
    color: '#F59E0B',
    fontWeight: '600',
    marginBottom: 10,
    textAlign: 'center',
  },
  streetFareRates: {
    backgroundColor: '#374151',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  streetFareRateText: {
    color: '#D1D5DB',
    fontSize: 13,
    textAlign: 'center',
  },
  streetFarePriceRange: {
    alignItems: 'center',
    marginBottom: 10,
  },
  streetFarePrice: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#10B981',
  },
  streetFareDistance: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 10,
  },
  streetFareDistanceText: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  streetFareWarning: {
    color: '#F59E0B',
    fontSize: 12,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  streetFareNavigateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginTop: 12,
    gap: 10,
  },
  streetFareNavigateText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // Time Range Dropdown styles
  timeRangeContainer: {
    position: 'relative',
    zIndex: 100,
  },
  timeRangeDropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1E293B',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  timeRangeDropdownButtonActive: {
    borderColor: '#10B981',
    backgroundColor: '#064E3B',
  },
  timeRangeDropdownText: {
    color: '#E2E8F0',
    fontSize: 13,
    fontWeight: '500',
  },
  timeRangeDropdownTextActive: {
    color: '#10B981',
  },
  timeRangeDropdownMenu: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 6,
    backgroundColor: '#1E293B',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
    width: 200,
    maxHeight: 300,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    zIndex: 1000,
  },
  timeRangeDropdownScroll: {
    maxHeight: 290,
  },
  timeRangeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  timeRangeOptionSelected: {
    backgroundColor: '#064E3B',
  },
  timeRangeOptionNow: {
    backgroundColor: '#1E3A5F',
  },
  timeRangeOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  timeRangeOptionText: {
    color: '#E2E8F0',
    fontSize: 14,
    fontWeight: '500',
  },
  timeRangeOptionTextSelected: {
    color: '#10B981',
    fontWeight: '600',
  },
  timeRangeOptionTextPast: {
    color: '#9CA3AF',
  },
  timeRangeOptionTextFuture: {
    color: '#60A5FA',
  },
  timeRangeOptionTextNow: {
    color: '#F59E0B',
    fontWeight: '600',
  },
  // Time Range Modal styles
  timeRangeModal: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    padding: 20,
    width: '90%',
    maxWidth: 400,
    maxHeight: '80%',
  },
  timeRangeModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 8,
  },
  timeRangeModalTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  timeRangeModalSubtitle: {
    color: '#9CA3AF',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 16,
  },
  timeRangeModalScroll: {
    maxHeight: 400,
  },
  timeRangeSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
    marginTop: 8,
  },
  timeRangeSectionTitle: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timeRangeModalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginVertical: 2,
  },
  timeRangeModalOptionSelected: {
    backgroundColor: '#064E3B',
  },
  timeRangeModalOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  timeRangeModalOptionText: {
    color: '#E2E8F0',
    fontSize: 15,
    fontWeight: '500',
  },
  timeRangeModalOptionTextSelected: {
    color: '#10B981',
    fontWeight: '600',
  },
  timeRangeModalCloseButton: {
    backgroundColor: '#374151',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  timeRangeModalCloseButtonText: {
    color: '#E2E8F0',
    fontSize: 16,
    fontWeight: '600',
  },
  // SOS Button styles
  sosButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#374151',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  sosButtonActive: {
    backgroundColor: '#EF4444',
  },
  // SOS Modal styles
  sosModalContent: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
  },
  sosTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  sosDescription: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 24,
    textAlign: 'center',
  },
  sosOptionOk: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#065F46',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    width: '100%',
    marginBottom: 12,
    gap: 12,
  },
  sosOptionOkText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  },
  sosOptionAlert: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#78350F',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    width: '100%',
    marginBottom: 12,
    gap: 12,
  },
  sosOptionTextContainer: {
    flex: 1,
  },
  sosOptionAlertText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  sosOptionAlertSubtext: {
    color: '#D1D5DB',
    fontSize: 12,
    marginTop: 2,
  },
  sosOptionEmergency: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7F1D1D',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    width: '100%',
    gap: 12,
  },
  sosOptionEmergencyText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  sosOptionEmergencySubtext: {
    color: '#FCA5A5',
    fontSize: 12,
    marginTop: 2,
  },
  sosOptionDisabled: {
    opacity: 0.5,
  },
  sosActiveHeader: {
    alignItems: 'center',
    marginBottom: 16,
  },
  sosActiveTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#EF4444',
    marginTop: 8,
  },
  sosActiveDescription: {
    fontSize: 14,
    color: '#D1D5DB',
    textAlign: 'center',
    marginBottom: 20,
  },
  sosResolveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B981',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    width: '100%',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 12,
  },
  sosResolveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  sosCancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  sosCancelButtonText: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  // Alert notification banner styles
  alertNotificationBanner: {
    position: 'absolute',
    top: 100,
    left: 10,
    right: 10,
    zIndex: 1000,
  },
  alertNotificationItem: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#EF4444',
  },
  alertNotificationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  alertNotificationTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  alertNotificationText: {
    color: '#D1D5DB',
    fontSize: 14,
    marginBottom: 12,
  },
  alertNotificationActions: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  alertNavigateButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3B82F6',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 6,
  },
  alertNavigateButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  alertCallButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EF4444',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 6,
  },
  alertCallButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  alertDismissButton: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  alertDismissText: {
    color: '#9CA3AF',
    fontSize: 13,
  },
  // Events Tab Styles
  eventsContainer: {
    flex: 1,
    paddingHorizontal: 15,
    paddingBottom: 20,
  },
  addEventButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EC4899',
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 20,
    gap: 8,
    shadowColor: '#EC4899',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  addEventButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  noEventsContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  noEventsText: {
    color: '#9CA3AF',
    fontSize: 18,
    fontWeight: '600',
    marginTop: 16,
  },
  noEventsSubtext: {
    color: '#6B7280',
    fontSize: 14,
    marginTop: 8,
  },
  eventCard: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  eventTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  eventTime: {
    color: '#6366F1',
    fontSize: 16,
    fontWeight: '700',
  },
  eventUsername: {
    color: '#9CA3AF',
    fontSize: 13,
  },
  eventBody: {
    marginBottom: 12,
  },
  eventLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  eventLocation: {
    color: '#F59E0B',
    fontSize: 15,
    fontWeight: '600',
    flex: 1,
  },
  eventDescription: {
    color: '#E2E8F0',
    fontSize: 14,
    lineHeight: 20,
  },
  eventFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#334155',
  },
  eventVotes: {
    flexDirection: 'row',
    gap: 16,
  },
  voteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#0F172A',
  },
  voteButtonActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
  },
  voteButtonActiveDislike: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
  },
  voteCount: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '600',
  },
  voteCountActive: {
    color: '#10B981',
  },
  voteCountActiveDislike: {
    color: '#EF4444',
  },
  deleteEventButton: {
    padding: 12,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderRadius: 8,
    marginLeft: 8,
  },
  // Add Event Modal
  addEventModal: {
    backgroundColor: '#1E293B',
    borderRadius: 24,
    padding: 24,
    width: '90%',
    maxWidth: 400,
  },
  addEventHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  addEventTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    marginTop: 12,
  },
  addEventSubtitle: {
    color: '#9CA3AF',
    fontSize: 14,
    marginTop: 4,
  },
  addEventForm: {
    gap: 16,
  },
  addEventInputGroup: {
    gap: 6,
  },
  addEventLabel: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 4,
  },
  addEventInput: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 14,
    color: '#FFFFFF',
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#334155',
  },
  addEventTextArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  addEventTimeInput: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0F172A',
    borderRadius: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#334155',
  },
  addEventTimeTextInput: {
    flex: 1,
    padding: 14,
    color: '#FFFFFF',
    fontSize: 15,
  },
  addEventButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  addEventCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#334155',
    alignItems: 'center',
  },
  addEventCancelButtonText: {
    color: '#94A3B8',
    fontSize: 16,
    fontWeight: '600',
  },
  addEventSubmitButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#EC4899',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  addEventSubmitButtonDisabled: {
    backgroundColor: '#4B5563',
  },
  addEventSubmitButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  // Admin Panel Styles
  activeTabAdmin: {
    backgroundColor: '#EF4444',
  },
  adminContainer: {
    flex: 1,
    paddingHorizontal: 15,
    paddingBottom: 20,
  },
  adminHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  adminHeaderTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  adminTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  // Admin Stats Row
  adminStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  adminStatCard: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    borderRadius: 12,
    gap: 4,
  },
  adminStatNumber: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '700',
  },
  adminStatLabel: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
  },
  // Admin Search
  adminSearchContainer: {
    marginBottom: 12,
  },
  adminSearchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E293B',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 10,
    borderWidth: 1,
    borderColor: '#334155',
  },
  adminSearchInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
  },
  // Admin Action Buttons
  adminActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  adminActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EF4444',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    gap: 8,
  },
  adminActionButtonSecondary: {
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: '#6366F1',
  },
  adminActionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  // Blocked Users Management Button
  adminBlockedUsersButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: '#EF4444',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  adminBlockedUsersButtonActive: {
    backgroundColor: '#EF4444',
  },
  adminBlockedUsersButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  adminBlockedUsersButtonText: {
    color: '#EF4444',
    fontSize: 15,
    fontWeight: '600',
  },
  // Blocked Users Section
  blockedUsersSection: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#374151',
  },
  blockedUsersLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 20,
  },
  blockedUsersLoadingText: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  blockedUsersStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  blockedUserStatCard: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 8,
  },
  blockedUserStatNumber: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  blockedUserStatLabel: {
    color: '#9CA3AF',
    fontSize: 11,
    marginTop: 2,
  },
  blockedUsersRefreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    marginBottom: 12,
  },
  blockedUsersRefreshText: {
    color: '#9CA3AF',
    fontSize: 13,
  },
  noBlockedUsers: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  noBlockedUsersText: {
    color: '#6B7280',
    fontSize: 14,
    marginTop: 10,
  },
  blockedUserCard: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#374151',
  },
  blockedUserCardPermanent: {
    borderColor: '#7F1D1D',
    backgroundColor: '#7F1D1D20',
  },
  blockedUserCardTemporary: {
    borderColor: '#F59E0B',
    backgroundColor: '#F59E0B10',
  },
  blockedUserCardExpired: {
    borderColor: '#374151',
    opacity: 0.7,
  },
  blockedUserHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  blockedUserInfo: {
    flex: 1,
  },
  blockedUserName: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  blockedUserUsername: {
    color: '#6B7280',
    fontSize: 13,
    marginTop: 2,
  },
  blockedUserLicense: {
    color: '#9CA3AF',
    fontSize: 12,
    marginTop: 4,
  },
  blockedUserStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: '#374151',
  },
  blockedStatusPermanent: {
    backgroundColor: '#7F1D1D',
  },
  blockedStatusTemporary: {
    backgroundColor: '#78350F',
  },
  blockedStatusExpired: {
    backgroundColor: '#1F2937',
  },
  blockedUserStatusText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  blockedUserStats: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 12,
  },
  blockedUserStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  blockedUserStatText: {
    color: '#9CA3AF',
    fontSize: 12,
  },
  // New blocked user styles
  blockReasonBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    alignItems: 'flex-end',
  },
  blockReasonBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },
  blockReasonBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
  },
  blockedUserStatsSection: {
    marginBottom: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  blockedUserStatsSectionTitle: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 6,
  },
  blockedUserAbuseMessage: {
    color: '#6B7280',
    fontSize: 11,
    fontStyle: 'italic',
    marginTop: 4,
  },
  blockedUserActions: {
    flexDirection: 'row',
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#374151',
  },
  unblockButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#10B98120',
    borderWidth: 1,
    borderColor: '#10B981',
  },
  unblockButtonText: {
    color: '#10B981',
    fontSize: 13,
    fontWeight: '600',
  },
  resetFraudButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#F59E0B20',
    borderWidth: 1,
    borderColor: '#F59E0B',
  },
  resetFraudButtonText: {
    color: '#F59E0B',
    fontSize: 13,
    fontWeight: '600',
  },
  blockedUsersLoadButton: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  blockedUsersLoadButtonText: {
    color: '#6366F1',
    fontSize: 14,
    fontWeight: '600',
  },
  // Admin Search Results
  adminSearchResults: {
    marginBottom: 16,
  },
  adminSectionTitle: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 12,
    marginTop: 8,
  },
  adminNoResults: {
    color: '#6B7280',
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: 20,
  },
  // User Avatar with Online Indicator
  userAvatarContainer: {
    position: 'relative',
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: '#1E293B',
  },
  userLicense: {
    color: '#94A3B8',
    fontSize: 12,
  },
  // Legacy styles kept for compatibility
  addUserButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EF4444',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    gap: 8,
  },
  addUserButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  userCard: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  userCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  userDetails: {
    gap: 6,
  },
  userName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  roleBadge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  roleBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  userActions: {
    flexDirection: 'row',
    gap: 8,
  },
  editUserButton: {
    padding: 8,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderRadius: 8,
  },
  deleteUserButton: {
    padding: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderRadius: 8,
  },
  userPhone: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#334155',
  },
  userPhoneText: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  roleSelector: {
    flexDirection: 'row',
    gap: 8,
  },
  roleOption: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: '#0F172A',
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  roleOptionActive: {
    backgroundColor: 'rgba(107, 114, 128, 0.3)',
    borderColor: '#6B7280',
  },
  roleOptionActiveMod: {
    backgroundColor: 'rgba(245, 158, 11, 0.3)',
    borderColor: '#F59E0B',
  },
  roleOptionActiveAdmin: {
    backgroundColor: 'rgba(239, 68, 68, 0.3)',
    borderColor: '#EF4444',
  },
  roleOptionText: {
    color: '#9CA3AF',
    fontSize: 13,
    fontWeight: '600',
  },
  roleOptionTextActive: {
    color: '#FFFFFF',
  },
  adminSubmitButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  // Registration styles
  switchAuthButton: {
    marginTop: 20,
    alignItems: 'center',
  },
  switchAuthText: {
    color: '#94A3B8',
    fontSize: 14,
  },
  switchAuthLink: {
    color: '#6366F1',
    fontWeight: '600',
  },
  registerButton: {
    backgroundColor: '#10B981',
  },
  registerShiftSection: {
    marginTop: 8,
    marginBottom: 8,
  },
  registerShiftLabel: {
    color: '#94A3B8',
    fontSize: 13,
    marginBottom: 10,
    marginLeft: 4,
  },
  registerShiftButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  registerShiftButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    backgroundColor: '#1E293B',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  registerShiftButtonActiveDay: {
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    borderColor: '#F59E0B',
  },
  registerShiftButtonActiveAll: {
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    borderColor: '#6366F1',
  },
  registerShiftButtonActiveNight: {
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    borderColor: '#8B5CF6',
  },
  registerShiftButtonText: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
  },
  registerShiftButtonTextActive: {
    color: '#FFFFFF',
  },
  // Profile button in settings
  profileButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 14,
    marginTop: 10,
  },
  profileButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileButtonInfo: {
    gap: 2,
  },
  profileButtonName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  profileButtonLicense: {
    color: '#9CA3AF',
    fontSize: 13,
  },
  // Profile Modal styles
  profileModalScrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  profileModal: {
    backgroundColor: '#1E293B',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  profileModalHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  profileModalTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '700',
    marginTop: 12,
  },
  profileModalSubtitle: {
    color: '#9CA3AF',
    fontSize: 14,
    marginTop: 4,
  },
  // Change Password Modal styles
  changePasswordModal: {
    backgroundColor: '#1E293B',
    borderRadius: 24,
    padding: 24,
    width: '90%',
    maxWidth: 400,
  },
  changePasswordHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  changePasswordTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    marginTop: 12,
  },
  changePasswordSubtitle: {
    color: '#9CA3AF',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  changePasswordForm: {
    gap: 12,
    marginBottom: 24,
  },
  changePasswordButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  changePasswordCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#0F172A',
    alignItems: 'center',
  },
  changePasswordCancelText: {
    color: '#94A3B8',
    fontSize: 16,
    fontWeight: '600',
  },
  changePasswordSaveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#10B981',
  },
  changePasswordSaveButtonDisabled: {
    backgroundColor: '#374151',
    opacity: 0.6,
  },
  changePasswordSaveText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  changePasswordButton: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#F59E0B40',
  },
  passwordMismatchText: {
    color: '#EF4444',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 4,
  },
  profileForm: {
    gap: 16,
  },
  profileInputGroup: {
    gap: 6,
  },
  profileInputLabel: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 4,
  },
  profileInput: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 14,
    color: '#FFFFFF',
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#334155',
  },
  profileShiftSelector: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  profileShiftOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    backgroundColor: '#0F172A',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  profileShiftOptionActiveDay: {
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    borderColor: '#F59E0B',
  },
  profileShiftOptionActiveAll: {
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    borderColor: '#6366F1',
  },
  profileShiftOptionActiveNight: {
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    borderColor: '#8B5CF6',
  },
  profileShiftOptionText: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
  },
  profileShiftOptionTextActive: {
    color: '#FFFFFF',
  },
  profileButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
  },
  profileCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#334155',
    alignItems: 'center',
  },
  profileCancelButtonText: {
    color: '#94A3B8',
    fontSize: 16,
    fontWeight: '600',
  },
  profileSaveButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#6366F1',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  profileSaveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  // Chat styles
  chatButton: {
    backgroundColor: '#6366F1',
    borderRadius: 10,
    padding: 10,
    marginRight: 10,
  },
  chatModal: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    width: '95%',
    maxWidth: 500,
    height: '80%',
    maxHeight: 600,
    overflow: 'hidden',
  },
  chatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  chatTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  chatChannelTabs: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  chatChannelTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#0F172A',
  },
  chatChannelTabActive: {
    backgroundColor: '#6366F1',
  },
  chatChannelTabText: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
  },
  chatChannelTabTextActive: {
    color: '#FFFFFF',
  },
  chatMessagesContainer: {
    flex: 1,
  },
  chatMessagesContent: {
    padding: 16,
    gap: 12,
  },
  chatLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  chatEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  chatEmptyText: {
    color: '#9CA3AF',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 12,
  },
  chatEmptySubtext: {
    color: '#6B7280',
    fontSize: 14,
    marginTop: 4,
  },
  chatMessage: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 12,
    maxWidth: '85%',
    alignSelf: 'flex-start',
  },
  chatMessageOwn: {
    backgroundColor: '#4F46E5',
    alignSelf: 'flex-end',
  },
  chatMessageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
    gap: 12,
  },
  chatMessageHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatMessageUsername: {
    color: '#F59E0B',
    fontSize: 12,
    fontWeight: '700',
  },
  chatMessageTime: {
    color: '#6B7280',
    fontSize: 11,
  },
  chatDeleteButton: {
    padding: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  chatBlockButton: {
    padding: 4,
    borderRadius: 4,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    marginRight: 4,
  },
  chatMessageText: {
    color: '#E2E8F0',
    fontSize: 14,
    lineHeight: 20,
  },
  chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 12,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: '#334155',
  },
  chatInput: {
    flex: 1,
    backgroundColor: '#0F172A',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: '#FFFFFF',
    fontSize: 14,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: '#334155',
  },
  chatSendButton: {
    backgroundColor: '#6366F1',
    borderRadius: 20,
    padding: 12,
  },
  chatSendButtonDisabled: {
    backgroundColor: '#4B5563',
  },
  chatReadOnlyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 14,
    backgroundColor: '#0F172A',
    borderTopWidth: 1,
    borderTopColor: '#334155',
  },
  chatReadOnlyText: {
    color: '#9CA3AF',
    fontSize: 13,
  },
  // License Alerts styles
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  // Radio styles
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderRadius: 10,
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: '#334155',
    gap: 4,
  },
  radioButtonConnected: {
    borderColor: '#10B981',
    backgroundColor: '#10B98120',
  },
  radioButtonTransmitting: {
    borderColor: '#EF4444',
    backgroundColor: '#EF4444',
  },
  radioChannelBadge: {
    color: '#10B981',
    fontSize: 12,
    fontWeight: 'bold',
  },
  radioModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  radioDropdownContainer: {
    position: 'absolute',
    top: 100,
    left: 10,
    right: 10,
    zIndex: 1000,
  },
  radioDropdown: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    width: '100%',
    maxWidth: 400,
  },
  radioDropdownHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  radioDropdownTitle: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  radioSectionLabel: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  radioChannelSelector: {
    marginBottom: 16,
  },
  radioChannelScroll: {
    marginBottom: 8,
  },
  radioChannelButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#0F172A',
    borderWidth: 2,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  radioChannelButtonActive: {
    borderColor: '#10B981',
    backgroundColor: '#10B98120',
  },
  radioChannelButtonBusy: {
    borderColor: '#F59E0B',
  },
  radioChannelButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  radioChannelButtonTextActive: {
    color: '#10B981',
  },
  radioChannelUserCount: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#6366F1',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioChannelUserCountText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  radioChannelName: {
    color: '#6B7280',
    fontSize: 12,
    textAlign: 'center',
  },
  radioUsersSection: {
    marginBottom: 16,
    padding: 12,
    backgroundColor: '#0F172A',
    borderRadius: 10,
  },
  radioUsersList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  radioUserBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#1E293B',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#334155',
  },
  radioUserBadgeTransmitting: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  radioUserName: {
    color: '#9CA3AF',
    fontSize: 12,
  },
  radioUserNameTransmitting: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  radioControlsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  radioControlButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#334155',
  },
  radioControlButtonConnect: {
    backgroundColor: '#10B98120',
    borderColor: '#10B981',
  },
  radioControlButtonDisconnect: {
    backgroundColor: '#EF444420',
    borderColor: '#EF4444',
  },
  radioControlButtonMute: {
    backgroundColor: '#0F172A',
    borderColor: '#334155',
  },
  radioControlButtonMuteActive: {
    backgroundColor: '#F59E0B20',
    borderColor: '#F59E0B',
  },
  radioControlButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  radioPTTButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    borderRadius: 16,
    backgroundColor: '#0F172A',
    borderWidth: 3,
    borderColor: '#10B981',
    // Prevent text selection and touch gestures on Android Chrome
    userSelect: 'none',
    WebkitUserSelect: 'none',
    WebkitTouchCallout: 'none',
    touchAction: 'none',
    cursor: 'pointer',
  } as any,
  radioPTTButtonDisabled: {
    borderColor: '#334155',
    backgroundColor: '#0F172A',
  },
  radioPTTButtonActive: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  radioPTTButtonBusy: {
    borderColor: '#F59E0B',
    backgroundColor: '#F59E0B20',
  },
  radioPTTText: {
    color: '#10B981',
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 8,
  },
  radioTransmittingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
    padding: 10,
    backgroundColor: '#F59E0B20',
    borderRadius: 10,
  },
  radioTransmittingText: {
    color: '#F59E0B',
    fontSize: 13,
  },
  // Games Styles
  gamesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderRadius: 10,
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: '#334155',
    marginLeft: 8,
  },
  gamesButtonActive: {
    borderColor: '#10B981',
    backgroundColor: '#10B98120',
  },
  gamesModalContainer: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  gamesModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: '#1E293B',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  gamesModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  gamesModalTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
  },
  gamesModalHeaderButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  gamesModalHeaderButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gamesModalCloseButton: {
    backgroundColor: '#EF4444',
  },
  gamesContent: {
    flex: 1,
  },
  gamesContentContainer: {
    padding: 16,
  },
  gamesSubtitle: {
    color: '#94A3B8',
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 24,
  },
  gamesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
  },
  gameCard: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 16,
    width: '47%',
    minWidth: 150,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
  },
  gameCardDisabled: {
    opacity: 0.5,
  },
  gameCardIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  gameCardTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  gameCardDescription: {
    color: '#94A3B8',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 8,
  },
  gameCardPlayers: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  gameCardPlayersText: {
    color: '#10B981',
    fontSize: 11,
  },
  gamesOnlineSection: {
    marginTop: 24,
    padding: 16,
    backgroundColor: '#1E293B',
    borderRadius: 12,
    alignItems: 'center',
  },
  gamesOnlineTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  gamesOnlineCount: {
    color: '#94A3B8',
    fontSize: 14,
  },
  gamesMinimizedBadge: {
    position: 'absolute',
    bottom: 100,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#6366F1',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 1000,
  },
  gamesMinimizedText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  gameInProgress: {
    flex: 1,
  },
  gameInProgressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 12,
  },
  gameBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#334155',
  },
  gameBackButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  gameInProgressTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    flex: 1,
  },
  gamePlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    backgroundColor: '#1E293B',
    borderRadius: 16,
    marginTop: 20,
  },
  gamePlaceholderTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 8,
  },
  gamePlaceholderText: {
    color: '#F59E0B',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
  },
  gamePlaceholderSubtext: {
    color: '#94A3B8',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 24,
  },
  gameStartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#6366F1',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
  },
  gameStartButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  alertsButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'transparent',
  },
  alertsButtonActive: {
    backgroundColor: '#F59E0B',
  },
  alertsModal: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    width: '95%',
    maxWidth: 500,
    height: '85%',
    maxHeight: 650,
    overflow: 'hidden',
  },
  alertsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  alertsModalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  alertsModalTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  alertsModalActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  markAllReadButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#334155',
    borderRadius: 8,
  },
  markAllReadText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
  },
  createAlertButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginHorizontal: 16,
    marginVertical: 12,
    paddingVertical: 12,
    backgroundColor: '#F59E0B',
    borderRadius: 12,
  },
  createAlertButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  alertsListContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  alertsLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  alertsEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  alertsEmptyText: {
    color: '#9CA3AF',
    fontSize: 18,
    fontWeight: '600',
    marginTop: 16,
  },
  alertsEmptySubtext: {
    color: '#6B7280',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  alertCard: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#334155',
  },
  alertCardUnread: {
    borderLeftColor: '#F59E0B',
    backgroundColor: '#1E293B',
  },
  alertCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  alertTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  alertTypeBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  deleteAlertButton: {
    padding: 6,
  },
  alertMessage: {
    color: '#E2E8F0',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 10,
  },
  alertSenderInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  alertSenderText: {
    color: '#9CA3AF',
    fontSize: 12,
  },
  alertTimeText: {
    color: '#6B7280',
    fontSize: 11,
  },
  unreadBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#EF4444',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 4,
  },
  unreadBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  // Create Alert Modal
  createAlertModal: {
    backgroundColor: '#1E293B',
    borderRadius: 24,
    padding: 24,
    width: '90%',
    maxWidth: 400,
  },
  createAlertHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  createAlertTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    marginTop: 12,
  },
  createAlertSubtitle: {
    color: '#9CA3AF',
    fontSize: 14,
    marginTop: 4,
  },
  createAlertForm: {
    gap: 16,
  },
  createAlertInputGroup: {
    gap: 6,
  },
  createAlertLabel: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 4,
  },
  createAlertInput: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 14,
    color: '#FFFFFF',
    fontSize: 15,
    borderWidth: 1,
    borderColor: '#334155',
  },
  createAlertTextArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  alertTypeSelector: {
    flexDirection: 'row',
    gap: 10,
  },
  alertTypeOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    backgroundColor: '#0F172A',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  alertTypeOptionActiveLost: {
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    borderColor: '#F59E0B',
  },
  alertTypeOptionActiveGeneral: {
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    borderColor: '#6366F1',
  },
  alertTypeOptionText: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
  },
  alertTypeOptionTextActive: {
    color: '#FFFFFF',
  },
  createAlertButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  createAlertCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#334155',
    alignItems: 'center',
  },
  createAlertCancelButtonText: {
    color: '#94A3B8',
    fontSize: 16,
    fontWeight: '600',
  },
  createAlertSendButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#F59E0B',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  createAlertSendButtonDisabled: {
    backgroundColor: '#4B5563',
  },
  createAlertSendButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  // License search styles
  licenseSearchContainer: {
    position: 'relative',
  },
  licenseInputSelected: {
    borderColor: '#10B981',
    borderWidth: 2,
  },
  licenseSearchSpinner: {
    position: 'absolute',
    right: 14,
    top: 14,
  },
  selectedRecipientBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 8,
    padding: 10,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  selectedRecipientText: {
    flex: 1,
    color: '#10B981',
    fontSize: 13,
    fontWeight: '600',
  },
  licenseSuggestionsContainer: {
    marginTop: 8,
    backgroundColor: '#0F172A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#334155',
    maxHeight: 180,
    overflow: 'hidden',
  },
  licenseSuggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E293B',
  },
  suggestionInfo: {
    flex: 1,
  },
  suggestionName: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  suggestionLicense: {
    color: '#9CA3AF',
    fontSize: 12,
    marginTop: 2,
  },
  noSuggestionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
    padding: 14,
    backgroundColor: '#0F172A',
    borderRadius: 8,
  },
  noSuggestionsText: {
    color: '#6B7280',
    fontSize: 13,
  },
});
